### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by demian85** [bertrandom/chrome-cookies-secure#1]
Can you make it work on Linux please? Is it just the file path or any other twisted logic is needed?
Thanks.

**Comment by demian85** [comment]
Great! it works and i don't know why! lol
It never asked me for my password... how did it decrypt the cookie?

**Comment by bertrandom** [comment]
Only OS X generates a random encryption password and stores it in the keychain, Linux uses the same password:

https://github.com/bertrandom/chrome-cookies-secure/blob/master/index.js#L61-L63

I just pushed a new version (1.1.0).

**Comment by demian85** [comment]
'peanuts' es the password for every user in the world? WTF? Then why in my Linux Mint when I start Chrome, a Kwallet dialog appears asking me for my password?

**Comment by bertrandom** [comment]
I believe that Chrome on Linux stores the passwords (the ones you fill out forms with) in kwallet but stores the cookies encrypted in the sqlite database. I agree though that it's just security theater, if they're going to encrypt them then they probably shouldn't use the same password for every installation. Maybe it simplifies the cross-platform code.

**Comment by TomasHubelbauer** [comment]
Do you know whether the same approach with Keytar would also work on Windows? I assume the random password would be stored in the DPAPI, but other than that, Windows support might be doable with largely the same code - maybe.

Also this is covered in other issues already but I figure I'll update it here as well: `peanuts` is no longer the Linux password, on Linux something called alternative keyrings is now used, but I don't know enough about Linux to know what the heck that is.

**Comment by daguej** [comment]
@TomasHubelbauer I have implemented Windows support in #17.
