### ISSUE TITLE
fails on google

### ISSUE THREAD

**Issue by Zibri** [bertrandom/chrome-cookies-secure#15]
If I run this:

chrome.getCookies('http://google.com', function(err, cookies) {
    console.log(cookies);
});

I get only SID and NID and not HSID and SSID (which are there)

any clues?

**Comment by bertrandom** [comment]
It works for me, can you try cloning the repo and running `node example/google.js`? Which OS are you using?

**Comment by Zibri** [comment]
Linux 4.19.31-041931-generic
Ubuntu 17.10
Chrome Version 74.0.3729.131 (Official Build) (64-bit)

It "sort of" works... go to google.com and use "EditThisCookie"
extension.
And you will see there are more cookies than the ones dumped.

**Comment by rubengmurray** [comment]
Hi Zibri,

It looks like you're not fully qualifying the URL as per the readme.md. You'll need to do that in order to see the full gamut of cookies.

Let us know if that works?

**Comment by rubengmurray** [comment]
@Zibri did you get this working? I'll close this off in a couple of weeks if no response. Please see comment above if you read this.

**Comment by rubengmurray** [comment]
Closing this due to lack of response and example not using fully qualified URL
