### ISSUE TITLE
Decryption failed. TODO: Error code

### ISSUE THREAD

**Issue by zhouzhili** [bertrandom/chrome-cookies-secure#18]
if i run:

```js
chrome.getCookies('https://www.google.com.hk', function(err, cookies) {
  console.log(cookies)
})
```

i get 

\node_modules\chrome-cookies-secure\index.js:314
						cookie.value = dpapi.unprotectData(encryptedValue, null, 'CurrentUser').toString('utf-8');
						                     ^
Error: Decryption failed. TODO: Error code
    at Statement.<anonymous> (d:\myCode\baiduAnswerPuppeteer\node_modules\chrome-cookies-secure\index.js:314:28)

browser: chrome 80.0.3987.87
How to solve this problem？？

**Comment by lovetofail** [comment]
Looks like Chrome 80 started to encrypt cookies in a different way. New encrypted string start with "v10"

![chrome cookies](https://user-images.githubusercontent.com/4531542/74065179-f5a46780-49fc-11ea-8d45-41a691401bdc.png)
