### ISSUE TITLE
Add a typescript definition file

### ISSUE THREAD

**Issue by fridaythx** [bertrandom/chrome-cookies-secure#23]
Add a typescript definition file, so we can get type inference supported by VSCode.

**Comment by Alieas-PC** [comment]
Can I have a pull request? I have already written definition file for it.

**Comment by rubengmurray** [comment]
This would be a good addition. I don't think @bertrandom actively maintains this repo anymore though. Could you make a PR with the definition file anyway? I'd be interested in taking a look.

**Comment by Alieas-PC** [comment]
I've made a new PR and pushed my code, please check it when you have time, thanks! @rubengmurray 
#24

**Comment by rubengmurray** [comment]
Merged to `master`
