### ISSUE TITLE
Support for custom configs and allowing Chromium/Blink browsers

### ISSUE THREAD

**Issue by rbndelrio** [bertrandom/chrome-cookies-secure#30]
This tool is extremely useful but my ideal use case would let me import cookies from [Brave](https://github.com/brave/brave-browser). Naturally, the sprawl of Chromium-based browsers is pretty wide so an ideal path for this might just be reorganizing the api to allow for custom paths like:

```js
const chromeish = require('chrome-cookies-secure');

const options = {
  format: 'curl',
  profile: 'Default',
  path: '/Library/Application Support/BraveSoftware/Brave-Browser',
  // Or override home path with fullPath
}
chromeish.getCookies('https://foo.com/', options, console.log);
```

An API structure like this would be ideal and it should be easy to maintain backwards compatibility. I may fork this project in a few weeks for my use case. Thanks!

**Comment by rubengmurray** [comment]
Hi @rbndelrio. This package now supports a custom path passed in using the existing `profile` argument. Whilst I like your `options` param a proposal PR was made as `profileOrPath` and that has now been merged in. See tests for usage.
