### ISSUE TITLE
No types file for chrome-cookies-secure

### ISSUE THREAD

**Issue by thisnamewasnottaken** [bertrandom/chrome-cookies-secure#35]
chrome-cookies-secure doesn't have a types file on @types/node

https://www.npmjs.com/package/@types/node

**Comment by rubengmurray** [comment]
There is an open PR here to add a declaration file however it's a little out of date.

I'll look into winding this into the repository soon.

https://github.com/bertrandom/chrome-cookies-secure/pull/24

**Comment by rubengmurray** [comment]
Also mentioned here https://github.com/bertrandom/chrome-cookies-secure/issues/23

**Comment by rubengmurray** [comment]
Merged to `master`
