### ISSUE TITLE
Cookies Database Moving in Chrome 96

### ISSUE THREAD

**Issue by ssddi456** [bertrandom/chrome-cookies-secure#38]
https://dfir.blog/cookies-database-moving-in-chrome-96/

The reason for this change is to enable sandboxing of Chrome's network service, so it can only access files on the file system that it needs. This would make it so any compromised network service can't access other files in the user's profile directory. Because of how ACLs work on Windows, to accomplish this the files needed by network services have moved from the user's profile directory to a Network subdirectory.

so there should be a cookie db detect or let user provide the path?

for now , we could pass '{the profile name}/Network' as profile parameter to bypass this issue

**Comment by mdpauley** [comment]
I submitted PR #39 to correct this. Hopefully it can be merged soon.

**Comment by thexeos** [comment]
I believe an approach like [this](https://pypi.org/project/mscookies/) would be more suitable. I have a patch that adds support for Edge, but a more generic solution would be ideal.

**Comment by rubengmurray** [comment]
I've pushed a new version to npm, `1.3.4 ` which has merged in #39. Please upgrade and let me know on here.

**Comment by rubengmurray** [comment]
I've tested this using:

- Node 12.18.4
- Chrome 102.0.5005.63
- Windows 11

All looks good to me.

Closing issue.
