### ISSUE TITLE
After a clean install it says "Cannot find module 'keytar'"

### ISSUE THREAD

**Issue by josep11** [bertrandom/chrome-cookies-secure#42]
```bash
npm i chrome-cookies-secure
```

The version is the latest, at the moment: 1.3.3

```js
const cookies = await chrome.getCookiesPromised(url, 'puppeteer', 'Default');
```

Throws error 

> Error: Cannot find module 'keytar'
Require stack:
> - /Users/.../node_modules/chrome-cookies-secure/index.js

**Comment by josep11** [comment]
If I manually install keytar with `npm i keytar` then it works.
I am using Mac OS X Monterrey 12.3.1

**Comment by rubengmurray** [comment]
What Node version? Seems OK to me running a very simplified version on Node `10.22.0`.

`keytar` is only used in the context of `darwin`/mac in the codebase so it's redundant for other OS but it would be interesting to know which Node version, I'm also on `Monterey 12.3.1`

**Comment by josep11** [comment]
Oh sorry, I forgot to share the Node version. It is `16.14.0`.

And it is so strange, now I created a new project from scratch with `chrome-cookies-secure` version `1.3.4` and it was working ...
I don't know the nitty gritty of how optional dependencies get handled but clearly here it did a strange job. I need to say that in the original project I had version 1.3.2 from the beginning, then I bumped into 1.3.3, whereas in this new project from scratch I started straight away from version `1.3.4`.

Thanks for the support!

**Comment by rubengmurray** [comment]
From the documentation I can find, `optionalDependencies` - if for some reason they fail to install - do not block the overall install pipeline and `npm` will carry on as if nothing happened:

https://docs.npmjs.com/cli/v7/configuring-npm/package-json#optionaldependencies

`keytar` is only required for `process.platform === darwin` so if it fails to install on `windows` or `linux`, that's fine, but when it fails on `macOS` that's just not going to work.

We also have `win-dpapi` where the same would apply to `windows`

I'm not sure on the technicalities of making certain dependencies required only on certain operating systems, but it seems safer at least to just move these to `dependencies` to eradicate the possibility of this happening.

**Comment by rubengmurray** [comment]
Turns out moving at least one of these (`win-dpapi`)  to `dependencies` completely breaks the install on macOS. `npm i` complains that the required dependency does not fit the platform.

I've reverted to `optionalDependencies`.

**Comment by rubengmurray** [comment]
@josep11 have you run into this problem since?

**Comment by josep11** [comment]
@rubengmurray I just checked and I cannot reproduce it with version `2.1.1`.
Perhaps you can close it ;)

**Comment by rubengmurray** [comment]
Thanks i'll close it
