### ISSUE TITLE
With new Chrome Version, cannot open Cookie Store

### ISSUE THREAD

**Issue by paskaran** [bertrandom/chrome-cookies-secure#59]
Currently its not possible to access the Cookies with Chrome Version 126.0.6478.127 (Official Build) (64-bit).

`[Error: SQLITE_CANTOPEN: unable to open database file
Emitted 'error' event on Database instance at:       
] {
  errno: 14,
  code: 'SQLITE_CANTOPEN'
}

Node.js v18.19.0`

**Comment by zhoukekestar** [comment]
Meet same issue, I just can't `cat ~/Library/Application Support/Google/Chrome/Default/Cookies` in my Mac. Always show `EPERM: operation not permitted`

The final solution is just turn off Safe Browsing by `chrome://settings/security`

![Image](https://github.com/user-attachments/assets/31c272ef-7cf4-499f-8077-c01ddeb49938)
