### ISSUE TITLE
Does the plugin still work? The decrypted characters are wrong

### ISSUE THREAD

**Issue by oliverhuynh** [bertrandom/chrome-cookies-secure#62]
Looks like the plugin doesn't work any more. The decrypted characters are wrong
-![Image](https://i.imgur.com/1XEtSmw.png)

**Comment by rubengmurray** [comment]
What OS & relevant versions?

- node
- chrome-cookies-secure
- operating system
- browser

Despite being the active maintainer I haven't used this in ~3 months so I can't confirm off the cuff

**Comment by palmerusaf** [comment]
Same issue on my end as well.
-     node 20.9.0
-     chrome-cookies-secure 2.1.1
-     operating system linux(ubuntu based pop-os 22)
-     browser Chrome Version 129.0.6668.100 (Official Build) (64-bit)

**Comment by oliverhuynh** [comment]
The issue can be fixed when opening chrome with argument --password-store=basic
However, your personal chrome profile will be affected. Password saving would not be saved. Your accounts will be logged out in most of the pages.
